### ISSUE TITLE
base64 url decoding of modulus of an RSA key fails when there is padding

### ISSUE THREAD

**Issue by kamal2311** [MicahParks/compatibility-keyfunc#2] opened 2022-04-14 01:47 UTC
Hi Micah,

I just noticed that this line causes certain RSA keys to be improperly decoded.
https://github.com/MicahParks/compatibility-keyfunc/blob/20a552bfae1a1c975f22610fc2fe486a264fc0c0/rsa.go#L35

https://go.dev/play/p/ZYvVSsX8Ues

Would you have a better solution than to trim the = from the end first?

**Comment by MicahParks** [comment] 2022-04-14 02:52
Are you able to provide me with a _public_ RSA key or JWKS that causes this error?

Also, would you please provide me with a link to the software that creates the JWKS? I'm assuming that would be open source.

Currently, I'm thinking the software that creates the JWKS you are using is not compliant with the relevant RFCs. I could see a software engineer making the mistake of using regular Base64 instead of Base64URL.

https://stackoverflow.com/a/55389212/14797322

**Comment by MicahParks** [comment] 2022-04-14 03:00
Sorry. On mobile. I didn't view your Go playground link before the first comment. The Base64 in the example isn't Base64URL, it's normal Base64. Which is against the specification for the RFC I've linked in the source code. If a JWKS contains this encoding of Base64 it's not spec compliant. If the code that produces this JWKS is open source, I'll open an issue for their project for you.

**Comment by MicahParks** [comment] 2022-04-14 03:01
I'll close this issue in the morning, but feel free to link me the JWKS server you are using, if it's open source 🙂

**Comment by kamal2311** [comment] 2022-04-14 03:25
Thank you for the prompt response. But, does not the base64url spec make padding (=) as optional? which means it is permitted? This is the JWKS in question.

```
{"keys":[{"kty":"RSA","use":"sig","kid":"hw1T/zfqTKIT2DYbY1vweU1sLxT4SmhsgkCsHq00Ix8=","n":"0P9Deg7S0HYuM7QdDOVpXycDErBfpPqxtxKURsNCyrtlopsbW3V-kXdQSj3_QXNaaJh9hTT9l46sl6e1x713ZMcBQI1-3xjfqSPK7POu21KIQG76eSt1A4xfOU7Wj_tfhaYuu_Axwr8RcmHCxNm0umqEIMjoyd1o30xBYkpeSCiaNnqpAldyzVVFox5WAkUaQo0GFmuf9RKddprIwtDSq4DpmlPV41Qe6NUBnQ5mZnWFsJohzpnI1YacpUUfdA7ZWbnEhg5ZKlb9hl80yPKQUBjVoeMZUuB1BDOyP-HBAQgmtCrCfsm26JX2bZtagl3xdy9yQNuIK9Ly75iSXIIrFw==","e":"AQAB","alg":"RS256"}]}

**Comment by MicahParks** [comment] 2022-04-14 03:28
There is the option to use a dirty hack, if absolutely required. The standard Base64 public key could be decoded using standard decoding, then re-encoded into Base64URL. Then fed into `keyfunc`. I don't recommend this. 

Also, there's the option of using "given keys". More on that in the `README.md`. I recommend this if you get the public key from a non-JWKS source.

Without knowing more, I'd guess that you're using closed source software to create your JWKS. It would be best to update that software to be spec compliant, but you could also fork this repo, then change the decode from standard Base64. That would be "digging the hole deeper" and probably be worse off in the long run.

**Comment by MicahParks** [comment] 2022-04-14 03:33
> Thank you for the prompt response. But, does not the base64url spec make padding (=) as optional? which means it is permitted? This is the JWKS in question.
> 
> ```
> {"keys":[{"kty":"RSA","use":"sig","kid":"hw1T/zfqTKIT2DYbY1vweU1sLxT4SmhsgkCsHq00Ix8=","n":"0P9Deg7S0HYuM7QdDOVpXycDErBfpPqxtxKURsNCyrtlopsbW3V-kXdQSj3_QXNaaJh9hTT9l46sl6e1x713ZMcBQI1-3xjfqSPK7POu21KIQG76eSt1A4xfOU7Wj_tfhaYuu_Axwr8RcmHCxNm0umqEIMjoyd1o30xBYkpeSCiaNnqpAldyzVVFox5WAkUaQo0GFmuf9RKddprIwtDSq4DpmlPV41Qe6NUBnQ5mZnWFsJohzpnI1YacpUUfdA7ZWbnEhg5ZKlb9hl80yPKQUBjVoeMZUuB1BDOyP-HBAQgmtCrCfsm26JX2bZtagl3xdy9yQNuIK9Ly75iSXIIrFw==","e":"AQAB","alg":"RS256"}]}

Hmmm maybe `=` is a legal character for Base64. I'll look into this further in the morning.

https://datatracker.ietf.org/doc/html/rfc4648#section-5

**Comment by MicahParks** [comment] 2022-04-14 03:44
This is a bug and I'm surprised nobody has caught it until now. Thank you for catching it.

> Would you have a better solution than to trim the = from the end first?

Yes, instead of `base64.RawURLEncoding.DecodeString`, `base64.URLEncoding.DecodeString` should be used instead.

The fix is simple, but I'll release soon when I have the tests sorted out.

**Comment by MicahParks** [comment] 2022-04-14 04:16
Actually, maybe a false alarm on the bug call...

[RFC 7517 says](https://datatracker.ietf.org/doc/html/rfc7517#section-1.1) it uses the definition of base64url from Section 2 of RFC 7515.

[Section 2 of RFC 7515](https://datatracker.ietf.org/doc/html/rfc7515#section-2) defines base64url encoding like this:
> with all trailing '=' characters omitted

So it seems it's not a bug, but I'm wondering if I should include it anyways, based on how simple it would be to implement and how I could see a software engineer not digging that deep.

By the way, changing all the `base64.RawURLEncoding` to `base64.URLEncoding` does not solve the problem, I believe the encoding then expects there to be padding when the key's length isn't perfectly divisible by the (block size?).

If I am going to implement client side padding stripping, it'd look like this:
```go
base64.RawURLEncoding.DecodeString(strings.TrimRight(keyBase64URL, "="))
```

Somewhat related, but talking about how to implement base64url without padding:
https://datatracker.ietf.org/doc/html/rfc7515#appendix-C

**Comment by MicahParks** [comment] 2022-04-14 15:08
Support for non-RFC compliant trailing base64url padding has been added in [v0.14.0](https://github.com/MicahParks/compatibility-keyfunc/releases/tag/v0.14.0).

**Closed as completed by MicahParks** 2022-04-14 15:09 UTC
Labels: enhancement
